# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YLCommonKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 忽略 pod 库中的警告
  inhibit_all_warnings!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'BGFMDB'
  
end

